### ISSUE TITLE
App crashes when trying to midi map from Korg nanoKontrol

### ISSUE THREAD

**Issue by acous** [vargaradu/Focusrite-Midi-Control#1]
I'm hoping to use my Korg nanoKontrol to adjust the volume on my Scarlett 6i6. I have the Midi Control app connected and approved. The window looks like this:
![screen shot 2019-01-12 at 15 44 47](https://user-images.githubusercontent.com/43856/51075254-00b58880-1681-11e9-9651-9a1a0f5f9f40.png)
I click "Start MIDI Map", and the button turns red. As soon as I touch a slider on my nanoKontrol, the app crashes. Here is some information from the crash report:
```
Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]

Application Specific Information:
Fatal error: Index out of range
```
Please let me know if there is any further information I could provide, or any steps I could follow to help with the issue. I'd be happy to pay a small fee if it gets solved. Thanks for your time!

**Comment by raduvarga** [comment]
@acous  I've pushed an update which should fix this issue.

**Comment by acous** [comment]
Thanks @vargaradu, the app no longer crashes. I still can't midi map from my nanokontrol however, but I've found another solution for the time being, so no worries!

**Comment by raduvarga** [comment]
I pushed another update to show the default names of the mixes, in your case I see the names are blank. You have to first select a mix from "Hardware outputs" then your input on the right side table.

**Comment by raduvarga** [comment]
@ acous  I've just released a completely new version that's much more stable and has more features, you can check it out here: https://www.raduvarga.com/software/focusrite-midi-control
